### ISSUE TITLE
Incorrect encoding for big unsigned int

### ISSUE THREAD

**Issue by hernanponcedeleon** [smackers/smack#545]
The following C code

`unsigned uint32_max;`
`uint32_max = 0xffffffff;`

is incorrectly converted to this boogie instruction

`$sub.i32(0, 1)`

The work-around from #187 works when using `UINT_MAX` (and thus the added regression tests pass), but if one replaces `UINT_MAX` from [this](https://github.com/smackers/smack/blob/develop/test/c/basic/sign_cast.c) test by the local variable above, it does not work.

**Comment by shaobo-he** [comment]
@hernanponcedeleon Please use the `--bit-precise` flag as the integer encoding inherently has this problem. The ``work-around'' in #187 simply handles a very restricted case where if SMACK finds a literal is used in unsigned comparisons, we convert it into its 2's complement form. For your code, since there's no uses of this variable and it gets compiled to LLVM's `i32`, SMACK simply faithfully translated it based on what LLVM presents -- -1.

**Comment by zvonimir** [comment]
I exchanged a few emails with Hernan about this. Currently their implementation that uses SMACK does not support bit-vectors.
I know this is a hard problem. The only way I can see us being able to resolve this is for clang not to make this optimization in the first place. Any other ideas?

**Comment by hernanponcedeleon** [comment]
Maybe some background: we are not using SMACK for the verification, we use it to transform C code to Boogie and then we use our tool for the verification.

**Comment by hernanponcedeleon** [comment]
FYI: using the llvm flag -o1 instead of -o0, the problems disappears since the constant is correctly converted

**Comment by shaobo-he** [comment]
> FYI: using the llvm flag -o1 instead of -o0, the problems disappears since the constant is correctly converted

I doubt that this would be a general solution as it doesn't work for the following program,

```C
unsigned foo(unsigned x) { return x * 2; }
                                    
int main() {                                                                    
  unsigned uint32_max;                                                          
  uint32_max = 0xffffffff;                                                      
  return foo(uint32_max);                                                       
} 
```

With `-O1` I still got `0xffffffff` translated into `-1`,

```llvm
; Function Attrs: norecurse nounwind readnone uwtable                           
define dso_local i32 @main() local_unnamed_addr #0 {                            
  %1 = tail call i32 @foo(i32 -1)                                               
  ret i32 %1                                                                    
}    
```

**Comment by shaobo-he** [comment]
@hernanponcedeleon I implemented a comprehensive fix (sort of) in `integer-encoding-fix-2020` branch. Please try it out and let me know if it helps.

**Comment by hernanponcedeleon** [comment]
Thanks @shaobo-he for putting the time on this!

I'm getting some errors (see below) when running the build script.
The build script works with no problem in the main branch.
There is an "Updated to LLVM 9" commit in your branch that seems not to be part of master yet. Might the llvm version update be the problem? I would expected the build script to take care of this, maybe there is some change missing there?

`*** SMACK BUILD: Building SMACK ***`
`Submodule path 'sea-dsa': checked out '39ddfbfcbc58287bca76bc7ff2539f7e97635eac'`
`...`
`[9/50] Building CXX object CMakeFiles/....dir/lib/smack/CodifyStaticInits.cpp.o`
`FAILED: CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o `
`/usr/bin/clang++  -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I../include -I../sea-dsa/include -I/usr/lib/llvm-8/include -std=c++11  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-exceptions -fno-rtti -Wno-undefined-var-template -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -w -fdiagnostics-color -g -fvisibility=hidden -O0 -MD -MT CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o -MF CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o.d -o CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o -c ../lib/smack/CodifyStaticInits.cpp`
`../lib/smack/CodifyStaticInits.cpp:34:11: error: member reference type 'llvm::Constant *' is a pointer; did you mean to use '->'?`
`          .getCallee());
          ^
          ->`
`../lib/smack/CodifyStaticInits.cpp:34:12: error: no member named 'getCallee' in 'llvm::Constant'
          .getCallee());
           ^`
`2 errors generated.`
`[10/50] Building CXX object CMakeFiles...r.dir/lib/smack/ExtractContracts.cpp.o`
`ninja: build stopped: subcommand failed.`

**Comment by shaobo-he** [comment]
> Thanks @shaobo-he for putting the time on this!
> 
> I'm getting some errors (see below) when running the build script.
> The build script works with no problem in the main branch.
> There is an "Updated to LLVM 9" commit in your branch that seems not to be part of master yet. Might the llvm version update be the problem? I would expected the build script to take care of this, maybe there is some change missing there?
> 
> `*** SMACK BUILD: Building SMACK ***`
> `Submodule path 'sea-dsa': checked out '39ddfbfcbc58287bca76bc7ff2539f7e97635eac'`
> `...`
> `[9/50] Building CXX object CMakeFiles/....dir/lib/smack/CodifyStaticInits.cpp.o`
> `FAILED: CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o `
> `/usr/bin/clang++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I../include -I../sea-dsa/include -I/usr/lib/llvm-8/include -std=c++11 -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-exceptions -fno-rtti -Wno-undefined-var-template -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -w -fdiagnostics-color -g -fvisibility=hidden -O0 -MD -MT CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o -MF CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o.d -o CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o -c ../lib/smack/CodifyStaticInits.cpp`
> `../lib/smack/CodifyStaticInits.cpp:34:11: error: member reference type 'llvm::Constant *' is a pointer; did you mean to use '->'?`
> ` .getCallee()); ^ ->`
> `../lib/smack/CodifyStaticInits.cpp:34:12: error: no member named 'getCallee' in 'llvm::Constant' .getCallee()); ^`
> `2 errors generated.`
> `[10/50] Building CXX object CMakeFiles...r.dir/lib/smack/ExtractContracts.cpp.o`
> `ninja: build stopped: subcommand failed.`

Yes, I think the integer encoding fix branch uses LLVM 9 instead of LLVM 8 which is used by the master branch. If you could upgrade the LLVM version, it should work.

**Comment by hernanponcedeleon** [comment]
I managed to compile it with llvm 9.
However I'm still getting a wrong result; do I need to pass any special flag?

Running
`smack -t -bpl test.bpl test.c `
on the following code
`int main() {
        unsigned uint32_max;
        uint32_max = 0xffffffff;
        return uint32_max;
}` 
still generates this
`procedure {:entrypoint} main() returns ($r: i32) {`
`$bb0:`
`  call $initialize();`
`  $r := $sub.i32(0, 1);`
`  $exn := false;`
`  return; }`

**Comment by shaobo-he** [comment]
> I managed to compile it with llvm 9.
> However I'm still getting a wrong result; do I need to pass any special flag?
> 
> Running
> `smack -t -bpl test.bpl test.c `
> on the following code
> `int main() { unsigned uint32_max; uint32_max = 0xffffffff; return uint32_max; }`
> still generates this
> `procedure {:entrypoint} main() returns ($r: i32) {`
> `$bb0:`
> ` call $initialize();`
> ` $r := $sub.i32(0, 1);`
> ` $exn := false;`
> ` return; }`

Yes, you need to enable `--wrapped-integer-encoding`. I'm sorry I forgot to mention it. But this flag doesn't change -1 to UINT_MAX, instead it adds modulo operations before integer comparisons. For example, if you add an assertion like `uint32_max > 0U`, SMACK reports an error without this flag whereas it's avoided using this flag. If you inspect the Boogie file, you'll see the arguments to `ugt.i32` is wrapped with `tou` function applications. This function converts an unbounded integer value to an unsigned value. This is a design choice to reduce the number of modulo operations to insert. If you need `uint32_max` to get `UNIT_MAX`, we can certainly implement it as well.

**Comment by hernanponcedeleon** [comment]
Yes, now it works and I get the tou wrapper in the functions.
Thanks!

**Comment by hernanponcedeleon** [comment]
I have a question about the wrapper. I noticed that (in some cases) you use a check w.r.t to some very big numbers.
```
function {:inline} $tou.i64(i: i64) returns (i64) { (if ((i >= 0) && (i < 18446744073709551616)) then i else $smod.i64(i, 18446744073709551616)) }
```
While this should not a problem for a "pure" integer encoding in an STM solver, I just noticed that Z3 only allow values (when calling ctx.mkInt()) that fit in a long.

I wonder is you have encountered any problems during verification due to this?

**Comment by shaobo-he** [comment]
> I have a question about the wrapper. I noticed that (in some cases) you use a check w.r.t to some very big numbers.
> 
> ```
> function {:inline} $tou.i64(i: i64) returns (i64) { (if ((i >= 0) && (i < 18446744073709551616)) then i else $smod.i64(i, 18446744073709551616)) }
> ```
> 
> While this should not a problem for a "pure" integer encoding in an STM solver, I just noticed that Z3 only allow values (when calling ctx.mkInt()) that fit in a long.
> 
> I wonder is you have encountered any problems during verification due to this?

Hi @hernanponcedeleon,

No, we haven't seen any problems related to this. Z3 should be able to handle arbitrarily large integers per SMT specifications. I think creating literals for large numbers using Z3 bindings could be cumbersome. For example, the numbers used in such functions need to be created by passing their string forms (i.e., using `Z3_mk_numeral`).

**Comment by hernanponcedeleon** [comment]
Ohhh I haven't noticed I can also pass Strings in the constructors.
Thanks for the hint.
